Repository hjdevelop/ClearLink, pull requests merged in 2023-09, with the labels that each got.

#9 Feat 필수구현기능 완료
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/clearlink/AddContactDialog.kt
  app/src/main/java/com/example/clearlink/ContactDetailFragment.kt
  app/src/main/java/com/example/clearlink/ContactListFragment.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFavoritesFragment.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFragment.kt
  app/src/main/java/com/example/clearlink/MainActivity.kt
  app/src/main/java/com/example/clearlink/MyPageFragment.kt
  app/src/main/java/com/example/clearlink/adapter/ContactListAdapter.kt
  app/src/main/java/com/example/clearlink/adapter/ContactListViewPagerAdapter.kt
  app/src/main/java/com/example/clearlink/adapter/ViewPagerAdater.kt
  app/src/main/java/com/example/clearlink/model/UserModel.kt
  app/src/main/res/layout/activity_contact_detail_fragment.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/rv_item.xml
Labels: enhancement

#10 [기능 추가] : 롱클릭시 다이얼로그로 삭제
  app/src/main/java/com/example/clearlink/ContactListInnerFavoritesFragment.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFragment.kt
  app/src/main/java/com/example/clearlink/adapter/ContactListAdapter.kt
  app/src/main/res/drawable/ic_clearlink.PNG
Labels: feature

#11 [기능 추가] : 전화, 문자, 이메일 보내기 기능
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/clearlink/ContactDetailFragment.kt
  app/src/main/res/layout/activity_contact_detail_fragment.xml
Labels: feature

#12 [기능 추가] : swipe to action
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/clearlink/ContactListFragment.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFavoritesFragment.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFragment.kt
  app/src/main/java/com/example/clearlink/MainActivity.kt
  app/src/main/java/com/example/clearlink/MyItemTouchHelperCallback.kt
  app/src/main/java/com/example/clearlink/adapter/ContactListAdapter.kt
  app/src/main/java/com/example/clearlink/adapter/ViewPagerAdater.kt
  app/src/main/res/drawable/ic_phone.png
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/rv_item.xml
Labels: feature

#14 [버그 수정] : 즐겨찾기 별 사라짐
  app/src/main/java/com/example/clearlink/ContactListInnerFavoritesFragment.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFragment.kt
  app/src/main/java/com/example/clearlink/adapter/ContactListAdapter.kt
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_contact_list_inner.xml
  app/src/main/res/layout/rv_item.xml
Labels: bug

#15 [기능 추가] : notification 기능 추가, data class 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/clearlink/AddContactDialog.kt
  app/src/main/java/com/example/clearlink/AlarmReceiver.kt
  app/src/main/java/com/example/clearlink/ContactDetailFragment.kt
  app/src/main/java/com/example/clearlink/ContactListFragment.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFragment.kt
  app/src/main/java/com/example/clearlink/MyPageFragment.kt
  app/src/main/java/com/example/clearlink/model/UserModel.kt
  app/src/main/res/drawable/selector_radio_button.xml
  app/src/main/res/drawable/selector_radio_text.xml
  app/src/main/res/layout/activity_contact_detail_fragment.xml
  app/src/main/res/layout/dialog_add_contact.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: feature

#16 [버그 수정] : 즐겨찾기 삭제 기능 수정
  app/src/main/java/com/example/clearlink/AddContactDialog.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFavoritesFragment.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFragment.kt
  app/src/main/java/com/example/clearlink/adapter/ContactListAdapter.kt
  app/src/main/java/com/example/clearlink/model/UserModel.kt
Labels: bug

#17 [기능 추가] : 연락처 불러오기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/clearlink/ContactDetailFragment.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFragment.kt
  app/src/main/res/drawable/ic_add_call.xml
  app/src/main/res/layout/activity_contact_detail_fragment.xml
  app/src/main/res/layout/fragment_contact_list_inner.xml
Labels: bug, feature

#19 [기능 추가] : 롱클릭 삭제시 즐겨찾기에서도 삭제되게 연동
  app/src/main/java/com/example/clearlink/ContactListInnerFavoritesFragment.kt
Labels: feature

#20 [PACK] : 🎁 프로젝트 최종
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/clearlink/ContactListInnerFavoritesFragment.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFragment.kt
  app/src/main/java/com/example/clearlink/adapter/ContactListAdapter.kt
  app/src/main/res/layout/activity_contact_detail_fragment.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: deploy

#21 [PACK] : 🎁 프로젝트 최종
  app/src/main/java/com/example/clearlink/AddContactDialog.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFavoritesFragment.kt
  app/src/main/java/com/example/clearlink/ContactListInnerFragment.kt
  app/src/main/java/com/example/clearlink/adapter/ContactListAdapter.kt
  app/src/main/res/drawable/ic_blueprofile.png
Labels: deploy
